FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.9-bookworm as builder

COPY requirements.txt /tmp/

RUN python3 -m pip install -r /tmp/requirements.txt 

ENV CONSUMER_KEY=''
ENV CONSUMER_SECRET=''
ENV ACCESS_TOKEN=''
ENV ACCESS_TOKEN_SECRET=''


WORKDIR /usr/src/app
COPY main.py main.py

CMD ["python3", "main.py"]




